  <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
  <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
  <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
  <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>



<style type="text/css">
  .titulo{
    font-size: 16px;
    font-weight: bold;
  }

  .st-btn{
    background-color: black; 
    color: #ffd700;
  }

  .st-bt-back{
    background-color: #ffd700; 
    color: black;   
  }

        .title-pdf{
            font-weight: bold;
            font-size: 13px;
        }
        .pdf-page {
            margin: 0 auto;
            box-sizing: border-box;
            box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
            background-color: #fff;
            color: #333;
            position: relative;
        }
        .pdf-header {
            position: absolute;
            top: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            /*border-bottom: 1px solid #e5e5e5;*/
        }
        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            padding-top: 10px;
            border-top: 1px solid #e5e5e5;
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            position: absolute;
            top: 4.3in;
            bottom: 1.2in;
            left: .5in;
            right: .5in;
        }

        .size-a4 { width: 8.3in; height: 11.7in; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 34px;
            font-weight: bold;
            color: black;
        }
        .for {
            position: absolute;
            top: 1.5in;
            left: .5in;
            width: 3.5in;
        }
        .from {
            position: absolute;
            top: 1.5in;
            right: .5in;
            width: 3.5in;
        }
        .from p, .for p {
            color: #787878;
        }
        .signature {
            padding-top: .5in;
        }

        .pdf-page {
            font-family: "DejaVu Sans", "Arial", sans-serif;
        }
</style>


<div class="row" style="margin-top: 15px;">
  <div class="col m12 s12">
    <a class="btn st-bt-back" href="javascript:window.history.go(-1);"><i class="material-icons left">arrow_back</i>Regresar</a>
  </div>
</div>

  <?php foreach ($this->info_correo as $key) {
    $id_correo = $key['id'];
    $nombre_correo = $key['nombre'];
    $email_correo = $key['email_personal'];
    $mensaje_correo = $key['mensaje'];
    $created_at = $key['created_at'];
    $status_leido = $key['status_leido'];
    $status_imp = $key['status_imp'];
  } ?>


<div class="row" style="margin-top: 30px;">
  <div class="col m12 s12 text-center">
    <span style="font-size:27px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle del Correo</span>
  </div>
</div>

<div class="row" style="margin-top: 20px;">
  <div class="col s12 m6">
    <div class="card" style="height: 230px;">
      <div class="card-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información</span>
        <div class="row" style="margin-top: 20px;">
          <div class="col m12 s12">
            <span class="titulo">Nombre:</span> <span><?php echo $nombre_correo; ?></span> <br>
            <span class="titulo">Correo:</span> <span><?php echo $email_correo; ?></span> <br>
            <span class="titulo">Fecha:</span> <span><?php echo $created_at; ?></span> <br>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 m6">
    <div class="card" style="height: 230px;">
      <div class="card-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Funciones</span>

        <div class="row" style="margin-top: 30px;">
          <div class="col m6 s12 text-center" style="margin-top: 3px;">
            <a class="btn st-btn"><i class="material-icons left">star_border</i>Favorito</a>
          </div>
          <div class="col m6 s12 text-center" style="margin-top: 3px;">
            <a class="btn st-btn"><i class="material-icons left">check_box</i>Favorito</a>
          </div>
        </div>

        <div class="row">
          <div class="col m12 s12 text-center">
            <a class="btn st-btn export-pdf"><i class="material-icons left" onclick="getPDF('.pdf-page')">file_download</i>Descargar</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m12">
    <div class="card">
      <div class="card-content">
        
        <div class="row">
          <div class="col m12 s12">
            <table>
              <thead>
                <tr>
                    <th>Mensaje</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td>
                    <span><?php echo $mensaje_correo; ?></span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

 <!-- P  D  F    s T Y L E -->

  <div class="row">
    <div class="col m12 s12">
      <span style="font-size:23px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Documento PDF</span>
    </div>
  </div>

    <div class="page-container hidden-on-narrow">
        <div class="pdf-page size-a4">
            <div class="pdf-header">
                <span class="company-logo">
                  <!-- <img src="/img/LogoSISP (7).png" style="width: 70px;" /><br/> -->
                </span>

                <div class="row">
                    <div class="company-logo col m12 s12 text-center">
                      <img src="/img/LogoSISP (7).png" style="width: 120px;" />
                    </div>
                </div>
            </div>
            <div class="pdf-footer">
                <p>
                  <!-- Fecha Footer -->
                </p>
            </div>
            <div class="for" style="margin-top: 60px;">
                <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información</span>
                <p>
                  <span class="titulo">Nombre:</span> <span><?php echo $nombre_correo; ?></span> <br>
                  <span class="titulo">Correo:</span> <span><?php echo $email_correo; ?></span> <br>
                  <span class="titulo">Fecha:</span> <span><?php echo $created_at; ?></span> <br>
                </p>
            </div>

            <div class="from" style="margin-top: 60px;">
              <div class="row">
                <div class="col m12 s12 text-center"> 
                  <!-- <img src="/img/LogoSISP (7).png" style="width: 90px;" /> -->
                </div>
              </div>

            </div>
            <div class="pdf-body">
                <div class="row">
                  <div class="col m12 s12" style="margin-top: 5px;">
                         <table>
                            <thead>
                              <tr style="background-color: white;">
                                  <th><span class="title-pdf">Mensaje</span></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <td><?php echo $mensaje_correo; ?></td>
                              </tr>
                            </tbody>
                          </table>
                  </div>
              </div>


                <div class="row signature">
                    <div class="col m12 s12 text-center">
                        <!-- <img src="/img/logo-2.png" style="width: 150px;"><br> -->
                    </div>
                </div>
            </div>
        </div>
    </div>


    
    <div class="responsive-message"></div>


    <script>
        // Import DejaVu Sans font for embedding

        // NOTE: Only required if the Kendo UI stylesheets are loaded
        // from a different origin, e.g. cdn.kendostatic.com
        kendo.pdf.defineFont({
            "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
            "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
            "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
            "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
        });
    </script>

    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="../content/shared/js/pako.min.js"></script>

    <script>
      function getPDF(selector) {
        kendo.drawing.drawDOM($(selector)).then(function(group){
          kendo.drawing.pdf.saveAs(group, "Mensaje No. <?php echo $id_correo; ?> .pdf");
        });
      }

    $(document).ready(function() {
        var data = [
          { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
          { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
          { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
          { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
          { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
          { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
        ];
        var schema = {
          model: {
            productName: { type: "string" },
            unitPrice: { type: "number", editable: false },
            qty: { type: "number" }
          },
          parse: function (data) {
                $.each(data, function(){
                    this.total = this.qty * this.unitPrice;
                });
                return data;
          }
        };
        var aggregate = [
          { field: "qty", aggregate: "sum" },
          { field: "total", aggregate: "sum" }
        ];
        var columns = [
          { field: "productName", title: "Product", footerTemplate: "Total"},
          { field: "unitPrice", title: "Price", width: 120},
          { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
          { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
        ];
        var grid = $("#grid").kendoGrid({
          editable: false,
          sortable: true,
          dataSource: {
            data: data,
            aggregate: aggregate,
            schema: schema,
          },
          columns: columns
        });

        $("#paper").kendoDropDownList({
          change: function() {
            $(".pdf-page")
              .removeClass("size-a4")
              .removeClass("size-letter")
              .removeClass("size-executive")
              .addClass(this.value());
          }
        });
    });
    </script>