<?php 
  function isActhref($nameBtn,$urlname){
      if($nameBtn==1 && $urlname==null){
        return "active"; 
      }
      return ($nameBtn == $urlname)?"active":"";
  }

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 
 
    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>





<style type="text/css">
  .oculto{display: none;}
  .active_menu{
  -webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
  -moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
  box-shadow: 0px 6px 3px -1px rgba(255,215,0,51);
  }

  .icon_style{
      font-size: 17px;
      font-family: "Nunito", sans-serif;
      cursor:pointer; 
  }

  .colorfont strong{
    color: rgb(169,68,66);
    font-weight: bold;
  }

  .colorfont span{
    color: rgb(169,68,66);
    font-weight: 350;
  }
  .st-btn{
    background-color: black; 
    color: #ffd700;
  }


</style>

<?php 
  $status = $this->op_bandeja; 
  $en_proceso = $this->count_correo;
?>

<div class="row" style="margin-top: 20px;">
	<div class="col m12 s12">
  		<ul >
  			<?php if($status == 0){ ?>
	    		<li class="tab col s3 active_menu">
	    			<a class="" href="/contacto/bandeja/op/0">
	    			<h4>Pendientes
	  					<div class="chip">
	    					<?php echo $en_proceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php }else{ ?>
	    		<li class="tab col s3">
	    			<a class="" href="/contacto/bandeja/op/0">
	    			<h4>Pendientes
	  					<div class="chip">
	    					<?php echo $en_proceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php } ?>

  			<?php if($status == 1){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/contacto/bandeja/op/1"><h4>Leidos</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/contacto/bandeja/op/1"><h4>Leidos</h4></a></li>
  			<?php } ?>

  			<?php if($status == 2){ ?>
  				<li class="tab col s3 active_menu"><a href="/contacto/bandeja/op/2"><h4>Importantes</h4></a></li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/contacto/bandeja/op/2"><h4>Importantes</h4></a></li>
  			<?php } ?>

  		</ul>
	</div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Bandeja de Correos</span>
    </div>
</div>


  <div class="row">
    <div class="col s12 m12">
      <div class="card">
        <div class="card-content">
          <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Correos</span>

          <div class="row">
            <div class="col m12 s12">
              <table class="table text-left table-hover">
                <thead>
                  <tr>
                    <th>NO.</th>
                    <th>Nombre</th>
                    <th>Correo</th>   
                    <th>Fecha</th>
                    <th>Empresa</th>
                    <th>Detalle correo</th>
                  </tr> 
                </thead>
                <?php
                if ($this->paginator) { 
                foreach ($this->paginator as $usr) { ?>
                <tbody>
                  <tr>
                    <td>
                      <h5><?php echo $usr['id']; ?></h5>
                    </td>
                    <td>
                      <h5><?php echo $usr['nombre']; ?></h5>
                    </td>
                    <td>
                      <h5><?php echo $usr['email_personal']; ?></h5>
                    </td>
                    <td>
                      <h5><?php echo $usr['fecha_envio']; ?></h5>
                    </td>
                    <td>
                      <h5><?php echo $usr['empresa']; ?></h5>
                    </td>

                    <td class="text-center">
                      <a href="/contacto/bandejadetail/id/<?php echo $usr["id"] ?>" class="st-btn btn  modal-trigger"><i class="fa fa-2x fa-id-card-o"></i></a>
                    </td>
                  </tr>
                  <?php } }else{ ?>
                  </tbody> 
                  <tbody>
                      <tr>
                          <td class="text-center" colspan="6"><h4>No se encontraron correos.</h4></td>
                      </tr>
                  </tbody>
                              
                  <?php } ?>
              </table>
            </div>
          </div>

          <div class="row">
              <div class="col m12 s12 text-center">
                  <div class="white-box">
                      <div class="paginationControl">
                          <ul class="pagination justify-content-center">
                            <?php if($pagina - 1 == 0){ ?>
                                <li class="page-item disabled">
                                    <span class="page-link">Anterior</span>
                                </li>
                            <?php }else{ ?>
                                  <li class="page-item">
                                      <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                                  </li>
                            <?php } ?>
                                  <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                                      <?php echo $links; ?>
                                  </li>
                            <?php if($pagina >= $this->total): ?>
                                  <li class="page-item disabled">
                                      <span class="page-link">Siguente</span>
                                  </li>
                              <?php else: ?>
                                  <li class="page-item">
                                      <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                                  </li>
                              <?php endif; ?>
                          </ul>
                      </div>
                  </div>
              </div> 
          </div>


        </div>
      </div>
    </div>
  </div>



