

<style type="text/css">
  .titulo{
    font-size: 16px;
    font-weight: bold;
  }

  .st-btn{
    background-color: black; 
    color: #ffd700;
  }

  .btn-st{
    background-color: #ffd700; 
    color: black;
  }

  .st-bt-back{
    background-color: #ffd700; 
    color: black;   
  }
</style>


<div class="row" style="margin-top: 15px;">
  <div class="col m12 s12">
    <a class="btn st-bt-back" href="javascript:window.history.go(-1);"><i class="material-icons left">arrow_back</i>Regresar</a>
  </div>
</div>

  <?php foreach ($this->info_correo as $key) {
    $id_correo = $key['id'];
    $nombre_correo = $key['nombre'];
    $email_correo = $key['email_personal'];
    $mensaje_correo = $key['mensaje'];
    $created_at = $key['created_at'];
    $status_leido = $key['status_leido'];
    $status_imp = $key['status_imp'];
  } ?>


<div class="row" style="margin-top: 30px;">
  <div class="col m12 s12 text-center">
    <span style="font-size:27px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle del Correo</span>
  </div>
</div>

<div class="row">
  <div class="col m12 s12 text-right">

    <?php if($status_imp == 0){ ?>

      <?php if($status_leido == 0 ){ ?>
      <p>
        <label>
          <input type="checkbox" id="leido" data-id="<?php echo $status_leido; ?>" value="<?php echo $id_correo ?>"/>
          <span>Marcar como leído</span>
        </label>
      </p>
      <?php }else{ ?>
      <p>
        <label>
          <input type="checkbox" checked id="leido" data-id="<?php echo $status_leido; ?>" value="<?php echo $id_correo ?>"/>
          <span>Marcar como leído</span>
        </label>
      </p>
      <?php } ?>

    <?php } ?>

  </div>
</div>


<div class="row" style="margin-top: 20px;">
  <div class="col s12 m6">
    <div class="card" style="height: 230px;">
      <div class="card-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información</span>
        <div class="row" style="margin-top: 20px;">
          <div class="col m12 s12">
            <span class="titulo">Nombre:</span> <span><?php echo $nombre_correo; ?></span> <br>
            <span class="titulo">Correo:</span> <span><?php echo $email_correo; ?></span> <br>
            <span class="titulo">Fecha:</span> <span><?php echo $created_at; ?></span> <br>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 m6">
    <div class="card" style="height: 230px;">
      <div class="card-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Funciones</span>

        <div class="row" style="margin-top: 30px;">
          <div class="col m6 s12 text-center" style="margin-top: 3px;">
            <?php if($status_imp == 0){ ?>
              <a class="btn st-btn" id="importante"><i class="material-icons left">star_border</i>Importantes</a>
            <?php }else{ ?>
              <a class="btn btn-st" id="importante"><i class="material-icons left">star_border</i>Importantes</a>
            <?php } ?>
            
          </div>
          <div class="col m6 s12 text-center" style="margin-top: 3px;">
            <a href="/contacto/descargacorreo/id/<?php echo $id_correo; ?>" class="btn st-btn export-pdf">Descargar</a>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m12">
    <div class="card">
      <div class="card-content">
        
        <div class="row">
          <div class="col m12 s12">
            <table>
              <thead>
                <tr>
                    <th>Mensaje</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td>
                    <span><?php echo $mensaje_correo; ?></span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<form action="/contacto/requestleido" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_check">
  <input type="hidden" name="id" value="<?php echo $id_correo ?>">
  <input type="hidden" name="op" id="op" value="">
</form>

<form action="/contacto/requestimportante" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_importante">
  <input type="hidden" name="id" value="<?php echo $id_correo ?>">
</form>

<script type="text/javascript">

    $('#leido').change(function() {//do something when the user clicks the box
      id=  $(this).data('id');
      document.getElementById('op').value = id;

      swal({
        text: "Espere un momento, su información esta siendo procesada!",
        icon: "success",
        button: false,
      });

      document.getElementById("submit_check").submit();

    });


    $("#importante").click(function(){
      swal({
        text: "Espere un momento, su información esta siendo procesada!",
        icon: "success",
        button: false,
      });

      document.getElementById("submit_importante").submit();
    });

</script>