<style type="text/css">
	.img-slider{
		width: 90px;
		height: 170px;
	}

  	.st-btn{
	    background-color: black; 
	    color: #ffd700;
  	}

</style>


<div class="row" style="margin-top: 20px;">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Clientes</span>
    </div>
</div>

<?php foreach ($this->quienessomos as $usr) { 
	$nombre_quienes = $usr['nombre'];
	$descripcion = $usr['descripcion'];
	$imagen = $usr['imagen'];
} ?>


<!-- M O D A L   C L I E N T E 1 -->
  	<div id="modal1" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente1">
		    	<input type="hidden" name="id" value="1">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[0]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[0]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[0]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente1" class="st-btn btn">Guardar</a>
	    </div>
  	</div>


<!-- M O D A L   C L I E N T E 2 -->
  	<div id="modal2" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente2">
		    	<input type="hidden" name="id" value="2">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[1]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[1]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[1]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente2" class="st-btn btn">Guardar</a>
	    </div>
  	</div>


<!-- M O D A L   C L I E N T E 3 -->
  	<div id="modal3" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente3">
		    	<input type="hidden" name="id" value="3">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[2]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[2]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[2]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente3" class="st-btn btn">Guardar</a>
	    </div>
  	</div>

<!-- M O D A L   C L I E N T E 4 -->
  	<div id="modal4" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente4">
		    	<input type="hidden" name="id" value="4">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[3]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[3]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[3]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente4" class="st-btn btn">Guardar</a>
	    </div>
  	</div>


<!-- M O D A L   C L I E N T E 5 -->
  	<div id="modal5" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente5">
		    	<input type="hidden" name="id" value="5">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[4]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[4]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[4]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente5" class="st-btn btn">Guardar</a>
	    </div>
  	</div>


<!-- M O D A L   C L I E N T E 6 -->
  	<div id="modal6" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente6">
		    	<input type="hidden" name="id" value="6">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[5]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[5]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[5]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente6" class="st-btn btn">Guardar</a>
	    </div>
  	</div>

<!-- M O D A L   C L I E N T E 7 -->
  	<div id="modal7" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente7">
		    	<input type="hidden" name="id" value="7">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[6]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[6]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[6]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente7" class="st-btn btn">Guardar</a>
	    </div>
  	</div>


<!-- M O D A L   C L I E N T E 8 -->
  	<div id="modal8" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente8">
		    	<input type="hidden" name="id" value="8">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[7]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[7]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[7]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente8" class="st-btn btn">Guardar</a>
	    </div>
  	</div>


<!-- M O D A L   C L I E N T E 9 -->
  	<div id="modal9" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente9">
		    	<input type="hidden" name="id" value="9">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[8]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[8]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[8]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente9" class="st-btn btn">Guardar</a>
	    </div>
  	</div>

<!-- M O D A L   C L I E N T E 10 -->
  	<div id="modal10" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente10">
		    	<input type="hidden" name="id" value="10">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[9]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[9]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[9]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente10" class="st-btn btn">Guardar</a>
	    </div>
  	</div>

<!-- M O D A L   C L I E N T E 11 -->
  	<div id="modal11" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente11">
		    	<input type="hidden" name="id" value="11">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[10]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="<?php echo $this->Clientes[10]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[10]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente11" class="st-btn btn">Guardar</a>
	    </div>
  	</div>

<!-- M O D A L   C L I E N T E 12 -->
  	<div id="modal12" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Logo/Nombre Cliente </span>

	    	<hr>
	    	<form action="/panel/requestudpcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cliente12">
		    	<input type="hidden" name="id" value="12">
		    	<div class="row" style="margin-top: 20px;">
		    		<div class="input-field col s2 m2 text-center"></div> 
		    		<div class="input-field col s8 m8 text-center">
			          	<input placeholder="Nombre Cliente" id="nombrec" name="nombrec" value="<?php echo $this->Clientes[11]['name_cliente'] ?>" type="text" class="validate">
			          	<label for="nombrec">Nombre Cliente</label>
			        </div>
			        <div class="input-field col s2 m2 text-center"></div>  
		    	</div>


		    	
		    	<div class="row">
		    		<div class="col m6 s12">
					    <div class="file-field input-field">
					      	<div class="btn">
					        	<span>Logo Cliente</span>
					        	<input type="file" name="file_mision">
					      	</div>
						    <div class="file-path-wrapper">
						        <input class="file-path validate" name="url_mision" value="/<?php echo $this->Clientes[11]['logo_cliente'] ?>" type="text">
						    </div>
					    </div>
		    		</div>
		    		<div class="col m6 s12 text-center">
		    			<img src="/<?php echo $this->Clientes[11]['logo_cliente'] ?>" width="150" heigh ="80">
		    		</div>	    	
		    	</div>
	    	</form>
	    </div>
	    <div class="modal-footer">
	    	<a href="#!" class="modal-close st-btn btn">Cancelar</a>
	    	<a id="udp_cliente12" class="st-btn btn">Guardar</a>
	    </div>
  	</div>

<div class="row">
	<div class="col s12 m12">
	    <div class="card">
		    <div class="card-content">
			    <table>
				    <thead>
				        <tr>
				            <th>Id</th>
				            <th>Nombre</th>
				            <th>Logo</th>
				            <th></th>
				        </tr>
				    </thead>

				    <tbody>
				        <tr>
				        	<td><?php echo $this->Clientes[0]['id'] ?></td>
				            <td><?php echo $this->Clientes[0]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[0]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal1" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[1]['id'] ?></td>
				            <td><?php echo $this->Clientes[1]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[1]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal2" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[2]['id'] ?></td>
				            <td><?php echo $this->Clientes[2]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[2]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal3" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[3]['id'] ?></td>
				            <td><?php echo $this->Clientes[3]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[3]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal4" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>

				        <tr>
				        	<td><?php echo $this->Clientes[4]['id'] ?></td>
				            <td><?php echo $this->Clientes[4]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[4]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal5" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[5]['id'] ?></td>
				            <td><?php echo $this->Clientes[5]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[5]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal6" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>

				        <!-- <tr>
				        	<td><?php echo $this->Clientes[6]['id'] ?></td>
				            <td><?php echo $this->Clientes[6]['name_cliente'] ?></td>
				            <td><img src="<?php echo $this->Clientes[6]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal7" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[7]['id'] ?></td>
				            <td><?php echo $this->Clientes[7]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[7]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal8" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[8]['id'] ?></td>
				            <td><?php echo $this->Clientes[8]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[8]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal9" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[9]['id'] ?></td>
				            <td><?php echo $this->Clientes[9]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[9]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal10" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[10]['id'] ?></td>
				            <td><?php echo $this->Clientes[10]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[10]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal11" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr>


				        <tr>
				        	<td><?php echo $this->Clientes[11]['id'] ?></td>
				            <td><?php echo $this->Clientes[11]['name_cliente'] ?></td>
				            <td><img src="/<?php echo $this->Clientes[11]['logo_cliente'] ?>" width="140" heigh ="70"></td>
				            <td><a href="#modal12" class="st-btn btn  modal-trigger"><i class="material-icons">edit</i></a></td>
				        </tr> -->
				    </tbody>
			   	</table>
		    </div>
	     </div>
	</div>
</div>


<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
  	$(document).ready(function(){
    	$('.modal').modal();
  	});


  	$("#udp_cliente1").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente1").submit();
  	});

  	$("#udp_cliente2").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente2").submit();
  	});

  	$("#udp_cliente3").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente3").submit();
  	});

  	$("#udp_cliente4").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente4").submit();
  	});

  	$("#udp_cliente5").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente5").submit();
  	});

  	$("#udp_cliente6").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente6").submit();
  	});

  	$("#udp_cliente7").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente7").submit();
  	});

  	$("#udp_cliente8").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente8").submit();
  	});

  	$("#udp_cliente9").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente9").submit();
  	});

  	$("#udp_cliente10").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente10").submit();
  	});

  	$("#udp_cliente11").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente11").submit();
  	});

  	$("#udp_cliente12").click(function(){
		swal({
			text: "Espere un momento, su información esta siendo procesada!",
			icon: "success",
			button: false,
		});

		document.getElementById("submit_cliente12").submit();
  	});


</script>