<div class="row mt-4">
	<div class="col m12 s12">
		<h2>Roles</h2>
	</div>
</div>

		<div class="col m12 s12">
			<form action="/panel/requestupdatenamerol" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_rol">
			<?php foreach ($this->roles as $usr) { ?>
			<input type="hidden" name="ids" value="<?php echo $usr["id"]; ?>">
				<div class="row">
			        <div class="input-field col m12 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="name" type="text" name="name" value="<?php echo $usr["nombre"]; ?>" class="validate" required>
			          	<label for="name">* Nombre(s):</label>
			        </div>
		      	</div>
		     <?php } ?>
		    </form>
		</div>

		<div class="input-field col m12 s12 text-right">
			<div class="row">
				<a href="/panel/usuarios" class="waves-effect red waves-light btn">Cancelar</a>
				<button  id="adduser" class="waves-effect waves-light btn">Actualizar</button>
			</div>	
		</div>


<script type="text/javascript">
    $("#adduser").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
                title: "Para editar un rol debes agregarle un nombre",
            });
        }else{
            swal("Felicidades!", "El rol se edito de forma correcta!", "success");   
            setTimeout(submitForm, 1500);     
        }

    });


    function submitForm() {
        document.getElementById("submit_rol").submit()
    }
</script>