<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<style type="text/css">
  .st-btn{
    background-color: black; 
    color: #ffd700;
  }

</style>

<div class="row mt-4">
	<div class="col m4 s12 text-center">
		<!-- <h2>Usuarios</h2> -->
	</div>

	<div class="col m8 s12 text-center" style="margin-top: 15px;">
		<div class="row">
			<div class="col m8 s6 text-right">
				<a class="st-btn btn modal-trigger" href="#modal1">+ Agregar Usuario</a>
			</div>
			<div class="col m4 s6 text-right">
				<a href="/panel/userrol" class="st-btn btn">+ Agregar Rol</a>
			</div>
		</div>
		
	</div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Usuarios</span>
    </div>
</div>

  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar usuarios</span>
		<div class="col m12 s12" style="margin-top: 19px;">
			<form action="/panel/requestadduser" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_usuario">
				<div class="row">
					<div class="input-field col s12">
					    <select id="rol" name="rol" required>
					      	<option value="0" disabled selected>* Selecciona una opcion:</option>
					      	<?php foreach ($this->rol as $rl) { ?>
					      	<option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?></option>
					      	<?php } ?>
					    </select>
					    <label>Rol del usuario</label>
					</div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="name" type="text" name="name" class="validate" required>
			          	<label for="name">* Nombre(s):</label>
			        </div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="ap" type="text" name="apa" class="validate" required>
			          	<label for="ap">* Apellidos Paterno:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="am" type="text" name="ama" class="validate" required>
			          	<label for="am">* Apellidos Materno:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">event_available</i>
			          	<input id="curp" type="text" name="curp" class="validate">
			          	<label for="curp">CURP:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">phone</i>
			          	<input id="phone" type="text" name="phone" class="validate">
			          	<label for="phone">Telefono</label>
			        </div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">email</i>
			          	<input id="mail" type="text" name="mail" class="validate" required>
			          	<label for="mail">* Correo Electronico</label>
			        </div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">vpn_key</i>
			          	<input id="pword" type="password" name="pword" class="validate" required>
			          	<label for="pword">* Contraseña</label>
			        </div>
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">vpn_key</i>
			          	<input id="pwordc" type="password" name="pwordc" class="validate" required>
			          	<label for="pwordc">* Confirmar Contraseña</label>
			        </div>
		      	</div>
		</div>
    </div>
    <div class="modal-footer">
      	
      	</form>
      	<button class=" btn st-btn" id="adduser">Guardar</button>
      	<button  class="modal-close st-btn btn">Cerrar</button>
    </div>
  </div>
<!-- ================================================================================================= -->

  <div class="row">
    <div class="col s12 m12">
      <div class="card">
        <div class="card-content">


<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
		<form action="/panel/searchusuarios" enctype="multipart/form-data" class="form-horizontal form-material">
	        <div class="input-field col m8 s8">
	          <input placeholder="Ingresa nombre" name="nombre" id="first_name" type="text" class="validate">
	          <label for="first_name">Buscar por Nombre</label>
	        </div>
	        <div class="input-field col m4 s4">
	        	<button tyle="submit" id="add_user" class="st-btn btn">Buscar <i class="material-icons left">search</i></button>
	        </div>
    	</form>
	</div>
	<div class="col m2 s12"></div>
</div>

        	
		<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de usuarios</span>
			<table class="table text-left table-hover">
			<thead>
				<tr style="background-color: #EDEDED">
					<th>Nombre</th>	
					<th>Apellido Paterno</th>	
					<!-- <th>Telefono</th> -->
					<th>Correo</th>
					<th>Rol</th>
					<th></th>
					<th></th>
					<th></th>
				</tr> 
			</thead>
			<?php foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo $usr["nombre"]; ?></td>
					<td><?php echo $usr["ap"]; ?></td>
					<!-- <td><?php echo $usr["telefono"]; ?></td> -->
					<td><?php echo $usr["correo"]; ?></td>
					<td><?php echo $usr["namerol"]; ?></td>
<!-- 					<td>
						<a href="/panel/usuariodetail/id/<?php echo $usr["id"] ?>" class="st-btn btn  modal-trigger"><i class="fa fa-2x fa-id-card-o"></i></a>

					</td> -->
					<td>
						<a href="/panel/usuariosedit/id/<?php echo $usr["id"] ?>" class="st-btn btn  modal-trigger"><i class="fa fa-2x fa-edit"></i></a>
					</td>
					<td>
						<a href="/panel/requestdeletealluser/id/<?php echo $usr["id"]; ?>" class="st-btn btn delete modal-trigger"><i class="fa fa-2x fa-trash"></i></a>
					</td>
				</tr>
			</tbody>
			<?php } ?>
		</table>

	<div class="row">
	    <div class="col m12 s12 text-center">
	        <div class="white-box">
	            <div class="paginationControl">
	                <ul class="pagination justify-content-center">
	               		<?php if($pagina - 1 == 0){ ?>
	                    	<li class="page-item disabled">
	                        	<span class="page-link">Anterior</span>
	                    	</li>
	               		<?php }else{ ?>
	                        <li class="page-item">
	                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
	                        </li>
	               		<?php } ?>
	                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
	                            <?php echo $links; ?>
	                        </li>
	               		<?php if($pagina >= $this->total): ?>
	                       	<li class="page-item disabled">
	                            <span class="page-link">Siguente</span>
	                       	</li>
	                    <?php else: ?>
	                        <li class="page-item">
	                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
	                        </li>
	                   	<?php endif; ?>
	                </ul>
	            </div>
	        </div>
	    </div> 
	</div>

        </div>
      </div>
    </div>
  </div>
            


<script type="text/javascript">
  $(document).ready(function(){
    $('.modal').modal();
     $('select').formSelect();
  });

    $(".delete").click(function(){
        var confirmar=confirm("Esta seguro que deseas eliminar");
        if(confirmar){
        	window.location.reload(true);
        }else{
            alert("cancelo la solicitud");
            return false;
        }
    });

        $("#adduser").click(function(){
        	var tipo = document.getElementById("rol").value;
            var name = document.getElementById("name").value;
            var ap = document.getElementById("ap").value;
            var am = document.getElementById("am").value;
            var mail = document.getElementById("mail").value;
            var pword = document.getElementById("pword").value;
            var pwordc = document.getElementById("pwordc").value;

            if(tipo == 0 || name == "" || ap == "" || am == "" || mail == "" || pword == "" || pwordc == "" || pword != pwordc){
                swal({
                  title: "Para agregar a un usuario debes llenar todos los campos marcados con un '*'",
                });
            }else{
            swal("Espere un momento, la información esta siendo procesada", {
                    icon: "success",
                    buttons: false,
            });    
                setTimeout(submitForm, 1500);     
            }

        });


        function submitForm() {
            document.getElementById("submit_usuario").submit()
        }
</script>
