
<?php $session = new Zend_Session_Namespace("current_session"); 
   
        $instance = new Application_Model_SeasonPanelModel();
        $id = $session->id;
        $wh ="id";
        $table = "usuario";
        $usuarios = $instance->GetSpecific($table,$wh,$id);

        $rol = $usuarios[0]['fkroles'];
        $wh = "id";
        $table = "roles";
        $rol_name = $instance->GetSpecific($table,$wh,$rol);
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="/img/LogoSISP (7).png"/>
    <title>SIS PROTEC</title>   
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/css/materialize.min.css">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/css/select2.min.css">
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/js/chart/dist/Chart.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    
    <script type="text/javascript" src="/js/jquery.v3.js"></script>
    <script type="text/javascript" src="/js/chart/Chart.min.js"></script>
    <script src ="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="/js/materialize.js"></script>
    <!-- <script type="text/javascript" src="/js/materialize.min.js"></script> -->
    <script src="/js/select2.min.js"></script>
    <link href="/css/lightbox.css" rel="stylesheet" />

    <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
    <script src="//cdn.ckeditor.com/4.5.9/standard/ckeditor.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.9/adapters/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"> </script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<body>

<style type="text/css">

body{
    background-color: white;
}

header, main, footer {
  padding-left: 300px; }

nav .bread {
  /*background-color: #B11C1C;*/
  padding-left: 20px; }

nav.top-nav h1.header {
  margin: 0;
  padding-top: 22px; }

.sidenav{
    height: calc(100% + 0px);
}
.sidenav li.active {
  background-color: #cccccc;
  color: #fff; }

.sidenav li.active a, .sidenav li.active a i {
  color: #fff; }

nav.top-nav {
  height: 70px; }

table.striped > tbody > tr:nth-child(2n+1) {
  background-color: rgba(234, 234, 234, 0.7); }

a.sidenav-trigger.top-nav {
  position: absolute;
  text-align: center;
  height: 48px;
  width: 48px;
  top: 5px;
  float: none;
  margin-left: 1.5rem;
  color: #fff;
  font-size: 36px;
  z-index: 2;
  left: 0; 
}

/*.oculto{
    display: none;
}
*/

.btn{

      margin-left: 7px;
      border-radius: 13px;
-webkit-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.19);
-moz-box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.19);
box-shadow: 10px 10px 5px 0px rgba(0,0,0,0.19);


}


thead>tr{
    background-color: #EDEDED;
}

.img-responsive{ max-width: 100%; }
.img-240{ width:120px; }

@media only screen and (max-width: 992px){header,main,footer{padding-left:0}}

body{
    background-color: white;
}

header, main, footer {
  padding-left: 300px; }

nav .bread {
  /*background-color: #B11C1C;*/
  padding-left: 20px; }

nav.top-nav h1.header {
  margin: 0;
  padding-top: 22px; }

.sidenav{
    height: calc(100% + 0px);
}

.sidenav::-webkit-scrollbar {
    -webkit-appearance: none;
}

.sidenav::-webkit-scrollbar:vertical {
    width:10px;
}

.sidenav::-webkit-scrollbar-button:increment,.sidenav::-webkit-scrollbar-button {
    display: none;
} 

.sidenav::-webkit-scrollbar:horizontal {
    display: none;/*height: 10px;*/
}

.sidenav::-webkit-scrollbar-thumb {
    background-color: #797979;
    border-radius: 20px;
    border: 2px solid #f1f2f3;
}

.sidenav::-webkit-scrollbar-track {
    border-radius: 10px;  
}

.sidenav li.active {
  background-color: #cccccc;
  color: #fff; }

.sidenav li.active a, .sidenav li.active a i {
  color: #fff; }

/* .sidenav li:hover a{
  background-color: #66BB6A;
  color: white;

  -webkit-transform: scale(1.1);
  -ms-transform: scale(1.1);
  transform: scale(1.1);
 /* border-radius: 15px 0px 15px 0px;
  box-shadow: inset 0 0 0 3px #555953;
}

.sidenav li:hover a i{
  background-color: #66BB6A;
  color: white;

}*/


nav.top-nav {
  height: 70px; }

table.striped > tbody > tr:nth-child(2n+1) {
  background-color: rgba(234, 234, 234, 0.7); }

a.sidenav-trigger.top-nav {
  position: absolute;
  text-align: center;
  height: 48px;
  width: 48px;
  top: 5px;
  float: none;
  margin-left: 1.5rem;
  color: #fff;
  font-size: 36px;
  z-index: 2;
  left: 0; 
}

.single-icon i:hover {
        /*transform: scale(1.5);*/
        /*color: #1813e4;*/
        color: blue;
    }
/*
.moves:hover {
    animation: moves 1s cubic-bezier(.36,.07,.57,.99) infinite;
}

@keyframes moves {
    0% {
        transform: scale(1) translateX(0);
    }
    15% {
        transform: scale(1) translateX(5px);
    }
    30% {
        transform: scale(1) translateX(-5px);
    }
    45% {
        transform: scale(1) translateX(3px);
    }
    60% {
        transform: scale(1) translateX(-3px);
    }
    75% {
        transform: scale(1) translateX(0);
    }
    100% {
        transform: scale(1) translateX(0);
    }
}*/


.img-responsive{ max-width: 100%; }
.img-240{ width:120px; }

@media only screen and (max-width: 992px){header,main,footer{padding-left:0}}

</style>

<!--  <script type="text/javascript">
var time = new Date().getTime();
$(document.body).bind("mousemove keypress", function () {
    time = new Date().getTime();
});

setInterval(function() {
    if (new Date().getTime() - time >= 80000) {
        window.location.reload(true);
    }
}, 1000);
</script> -->


<script type="text/javascript">
        
        $(document).ready(function(){
            $('.sidenav').sidenav();
        });
        
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.dropdown-trigger');
            var instances = M.Dropdown.init(elems, options);
            var sidenav = document.querySelectorAll('.sidenav');
            var snIns = M.Sidenav.init(sidenav);            
        });

        $(window).on("load",function(){
            $(".fade-screen").delay(700).fadeOut(400);
        });

        document.addEventListener('DOMContentLoaded', function() {
             var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems, { });
        });         
</script>

    <body>

<body>
    <style type="text/css">
        .active-menu{background-color: rgba(0,0,0,0.05);}
        .p20{ padding:20px;}
        .text-right{ text-align: right; }
        .text-left{ text-align: left; }
        .text-center{ text-align: center; }
        .inner-padding{ padding-top: 30px; }
    </style>
    <header>    
        <nav class="top-nav black">
            <div class="row">
                <div class="col m6 s6">
                    <h2 style="color:white;"><?php echo $rol_name[0]['nombre'];?> </h2>
                </div>
                <div class="col m6 s6 text-right">
                    <h2 style="color:white;" id="MyClockDisplay" class="clock" onload="showTime()"></h2>
                </div>
            </div>

        </nav>

<?php 

    $actual_link = "$_SERVER[REQUEST_URI]";
    // var_dump($actual_link);exit;
    $filename = substr(strrchr($actual_link, "/"), 1);


    function getUrl($nameBtn,$urlname){
        if($nameBtn == 1 && $urlname == null){ return "active"; }
        return ($nameBtn == $urlname)?"active":"";

    }

    function getcontacto($actual_link){
        $actual_link = "$_SERVER[REQUEST_URI]";
        $filename = substr(strrchr($actual_link, "/"), 1);
        $urldetail = "/contacto/bandeja/op/".$filename."";
        if($actual_link == $urldetail){ return "active"; }

        $urledit = "/contacto/bandejadetail/id/".$filename."";
        if($actual_link == $urledit){ return "active"; } 
 
    }

    function getservicio($actual_link){
        $actual_link = "$_SERVER[REQUEST_URI]";
        $filename = substr(strrchr($actual_link, "/"), 1);

        $urledit = "/servicios/editarprincipal/id/".$filename."";
        if($actual_link == $urledit){ return "active"; }

        $urledit = "/servicios/crearservicio";
        if($actual_link == $urledit){ return "active"; } 
 
        $urledit = "/servicios/editarservicio/id/".$filename."";
        if($actual_link == $urledit){ return "active"; } 
    }


?>
    <?php $year=date("Y"); ?>
        <div class="container">
            <a href="#" data-target="slide-out" class="top-nav sidenav-trigger full hide-on-large-only"><i class="material-icons">menu</i></a>
        </div>
        <ul id="slide-out" class="sidenav sidenav-fixed">
            <li class="logo text-center center" style="margin-bottom: 40px; margin-top: 20px;">
                <a href="/panel/index/year/<?php echo $year; ?>">
                    <img src="/img/Sispro (9).png" style="width: 70px;">
                </a> 
            </li>
                
            <li class="bold moves">
                <a href="/index/logout" style="color:red;">Cerrar Sesion <i class="material-icons" style="color:red;">highlight_off</i></a>
            </li>
                
            <li class="bold moves <?php echo getUrl('/panel/index',$actual_link);?>">
                <a href="/panel/index/year/<?php echo $year; ?>">Dashboard <i class="material-icons">extension</i></a>
            </li>
            
            <li class="bold moves <?php echo getUrl('/panel/usuarios',$actual_link);?>">
                <a href="/panel/usuarios">Usuarios <i class="material-icons">person</i></a>
            </li>

            <li class="bold moves <?php echo getUrl('/contacto/bandeja',$actual_link); echo getcontacto($actual_link);?>">
                <a href="/contacto/bandeja">Contacto <i class="material-icons">contact_mail</i></a>
            </li> 

            <li class="bold moves <?php echo getUrl('/quienes/index',$actual_link);?>">
                <a href="/quienes/index">Principal <i class="material-icons">announcement</i></a>
            </li>  

            <li class="bold moves <?php echo getUrl('/panel/clientes',$actual_link); echo getservicio($actual_link);?>">
                <a href="/panel/clientes">Clientes <i class="material-icons">person_pin</i></a>
            </li> 

            <li class="bold moves <?php echo getUrl('/servicios/servicios',$actual_link); echo getservicio($actual_link);?>">
                <a href="/servicios/servicios">Servicios <i class="material-icons">assignment</i></a>
            </li>   
        </ul>                  

</header>

<main>
    <nav class="">
        <div class="row nav-wrapper bread" style="width: 101%; background-color: #ffd700 ;"></div>      
    </nav>  
    <div class="container-fluid">         
        <div class="row">
            <div class="col m12 s12">
                <div class="row">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </div>      
</main>

<meta name="__token" content="{!! csrf_token() !!}" />  
<script type="text/javascript" src="/js/script.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">

$('.dropdown-trigger').dropdown();

    function destroyIt(formulario){
        swal({
            title: "Borrar registro",
            text: "¿Deseas eliminar el elemento seleccionado?\nEsta acción ya no se puede deshacer",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                /*
                swal("Poof! Your imaginary file has been deleted!", {
                    icon: "success",
                });
                */
                document.getElementById(formulario).submit();   
            } else {
                //swal("Se ha cancelado la elimininación");
            }
        });

    }
    
    function destroyImages(){


        var atLeastOneIsChecked = $('input[name="checkImg[]"]:checked').length;
        var ArryCheck = $('input[name="checkImg[]"]:checked');
        if(atLeastOneIsChecked > 0 ){

        swal({
            title: "Borrar imágenes",
            text: "¿Deseas eliminar los elementos seleccionado(s)?\nEsta acción ya no se puede deshacer",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                /*
                swal("Poof! Your imaginary file has been deleted!", {
                    icon: "success",
                });
                */
                var dataArray = [];
                ArryCheck.each(function(index, element){
                    //console.log(element);
                    dataArray[index] = $(element).data('id');
                    console.log($(element).data('id'));
                });

                $.post( "/panel/vehiculos/eraseimages", { 'items[]': dataArray })
                    .done(function( data ) {
                        console.log(data);
                        window.location.reload();
                });


            } else {
                //swal("Se ha cancelado la elimininación");
            }
        });         

        } else {

        swal({
            title: "",
            text: "No has seleccionado ninguna imagen",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        });

        }

        return false;

    }

</script>

<script type="text/javascript">
function showTime(){
    var date = new Date();
    var h = date.getHours(); // 0 - 23
    var m = date.getMinutes(); // 0 - 59
    var s = date.getSeconds(); // 0 - 59
    var session = "AM";
    
    if(h == 0){
        h = 12;
    }
    
    if(h > 12){
        h = h - 12;
        session = "PM";
    }
    
    h = (h < 10) ? "0" + h : h;
    m = (m < 10) ? "0" + m : m;
    // s = (s < 10) ? "0" + s : s;
    
    var time = h + ":" + m + " " + session;
    document.getElementById("MyClockDisplay").innerText = time;
    document.getElementById("MyClockDisplay").textContent = time;
    
    setTimeout(showTime, 1000);
    
}

showTime();
</script>

</body>
    </body>
    </html>