<?php $session = new Zend_Session_Namespace("current_session"); ?>

<!DOCTYPE html>

<html lang="es">

<head>
  <title>SIS PROTECT</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  <link rel="shortcut icon" href="/img/LogoSISP (7).png" />

</head>

<body>


<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top " style="background: black;">

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" 
  aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <a class="navbar-brand" href="#"><img src="/img/LogoSISP (3).png" height="40px"></a>
  
  <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
  
    <ul class="navbar-nav flex-row w-100">
  
      <li class="nav-item px-2 mr-auto active">
  
        
  
      </li>
  
      <li class="nav-item px-2">
  
        <a class="nav-link" href="#">Quienes somos</a>
  
      </li>

      <li class="nav-item px-2">
  
        <a class="nav-link" href="#">Servicios</a>
  
      </li>

      <li class="nav-item px-2">
  
        <a class="nav-link" target="_blank" href="/home/_contacto">Contacto</a>
  
      </li>

      <li class="nav-item px-2">
  
        <a class="nav-link" target="_blank" href="/panel">Sistema de Gestion</a>
  
      </li>
  
      
  
    </ul>
  
  </div>

</nav>

<div class="container" style="padding-top: 100px;">

  <?php echo $this->layout()->content; ?>

</div>  

<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

</body>
</html>







