<?php $session = new Zend_Session_Namespace("current_session"); ?>

<!DOCTYPE html>

<html lang="es">

<head>
  <title>SIS PROTECT</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  <link rel="shortcut icon" href="/img/LogoSISP (7).png" />

</head>

<style>

  .color{

    color: #DCB34E;

  }

</style>

<body>


<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top " style="background: black;">

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" 
  aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <a class="navbar-brand" href="#"><img src="/img/LogoSISP (3).png" height="40px"></a>
  
  <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
  
    <ul class="navbar-nav flex-row w-100">
  
      <li class="nav-item px-2 mr-auto active">
  
        
  
      </li>
  
      <li class="nav-item px-2">
  
        <a class="nav-link color" href="#" style="color: #DCB34E;">Quienes somos</a>
  
      </li>

      <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" style="color: #DCB34E;">Servicios</a>
        
        <div class="dropdown-menu">

          <a class="dropdown-item" href="#"><small>SIS TRACK</small></a>
          <a class="dropdown-item" href="#"><small>CUSTODIA DE MERCANCÍAS EN TRANSÍTO</small></a>
          <a class="dropdown-item" href="#"><small>CONSULTORÍA EN ESTÁNDARES DE GESTIÓN</small></a>
          <a class="dropdown-item" href="#"><small>CONSULTORÍA EN PROCESOS DE SEGURIDAD</small></a>
          <a class="dropdown-item" href="#"><small>CAPACITACIÓN ESPECIALIZADA ANÁLISIS</small></a> 
          <a class="dropdown-item" href="#"><small>ANÁLISIS DE VULNERABILIDAD Y GESTIÓN DE RIESGOS SECURITY</small></a>
          <a class="dropdown-item" href="#"><small>AUDITORIA DE CONTROL Y SEGURIDAD</small></a>
          <a class="dropdown-item" href="#"><small>RASTREOS</small></a>
        
        </div>

      </li>


      <li class="nav-item px-2">
  
        <a class="nav-link" target="_blank" href="/home/_contacto" style="color: #DCB34E;">Contacto</a>
  
      </li>

      <li class="nav-item px-2">
  
        <a class="nav-link" target="_blank" href="/panel" style="color: #DCB34E;">Sistema de Gestion</a>
  
      </li>
  
      
    </ul>
  
  </div>

</nav>

<div class="container-fluid" style="padding-top: 100px;">

  <?php echo $this->layout()->content; ?>

</div>  

<!-- Footer -->
<footer class="" style="background-color: #000000;">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© SIS PROTECT:
    <a href="http://dev.sisprotec.mx"> sisprotec.mx</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

</body>
</html>







