<div class="row" style="padding: 5%;">

    <form role="form" method="POST" action="/quienes/update" id="FormData"  enctype="multipart/form-data">

    	<input type="hidden" name="optReg" value="set">

        <input type="hidden" id="catId" name="ID_TEXTO" value="<?php print @$this->aData[0]['ID_TEXTO'] ?>">

        <div class="row">

            <div class="col s8 m8">
                    
                <div class="row">

                    <div class="col s12 m12">

                        <div class="form-group">

                            <label for="inputNOMBRE" class="col-xs-3 col-md-3 col-sm-3">Titulo</label>

                            <div class="input-group col-xs-9 col-md-9 col-sm-9">

                                <input class="form-control required" name="TITULO" placeholder="Titulo" value="<?php print @$this->aData[0]['TEXTO_TITULO'] ?>">

                                <div class="form-group">

                                </div>   

                            </div>

                        </div>
                        
                        <div class="form-group">

                            <label for="inputDESCRIPCION" class="col-xs-3 col-md-3 col-sm-3">Descripción Texto</label>

                            <div class="input-group col-xs-9 col-md-9 col-sm-9">

                                <textarea  class="form-control" name="DESCRIPCION" placeholder="Descripcion Texto" value=""  rows="30" cols="50"><?php print @$this->aData[0]['TEXTO'] ?></textarea> 

                            </div>

                        </div> 

                        <div class="form-group">

                            <label for="inputDESCRIPCION" class="col-xs-3 col-md-3 col-sm-3"> Selecciona un color</label>

                            <div class="input-group col-xs-9 col-md-9 col-sm-9">

                                <input name="COLOR" type="color" value="<?php print @$this->aData[0]['COLOR'] ?>"> </input>

                            </div>

                        </div> 

                    </div>

                </div>
                
            </div>

        </div>

        <div class="box-footer col-xs-12 col-md-12 col-sm-12">

            <button type="submit" class="green darken-2 btn-small">Guardar Información</button>

            <a type="button" class="deep-orange darken-4 btn-small" href="/quienes">Regresar</a>

        </div>

	<form>

    <?php if( @$this->aResponse['status'] == 1 ):?>

        <script>

           $(document).ready( function(){
              
              success();
           
           });

        </script>

    <?php elseif (@$this->aResponse['status'] == -1):?>

        <script>

           $(document).ready( function(){
              
              danger();
           
           });

        </script>

    <?php endif; ?>

</div>


<script type="text/javascript">
    
    function success(){

        swal({

            icon: "success",

            text: "Se Registro de manera Correcta",

        });

    }

    function danger(){

        swal({

            icon: "error",

            text: "Ocurrio un error al registrar el producto",

        });

    }
    
</script>
