<div class="col-md-12">
    <h2>Mis Compras</h2>
    <table class="table table-bordered table-striped">                    
        <thead>
            <tr>
                <th>Orden</th>
                <th>Nombre</th>
                <th>Usuario</th>
                <th>Direccion</th>
                <th>Detalles</th>
                
            </tr>
        </thead>
        <tbody>
            <?php if ($this->complete) { ?>
            <tbody>
            <?php foreach($this->complete as $k){ ?>
                    <tr>
                        <td><p><?php echo $k["idorden"];?></p></td>
                        <td><p><?php echo $k["nombre"]; ?></p></td>
                        <td><p><?php echo $k["name"]; ?></p></td>
                        <td><p><?php echo $k["direccion"];?></p></td>
                        
                        <td>
                            <a href="/home/detallespedidos/id/<?php echo $k["idusuario"]; ?>/idorden/<?php echo $k["idorden"]; ?>"><i class="fa fa-info" style="color: blue;">Detalles</i></a>
                        </td>                        
                    </tr>    
            <?php } } else{ ?>
            <tbody>
                <tr>
                    <td colspan="5"><h3>No hay ninguna compra realizada.</h3></td>
                </tr>
            </tbody> 
            <?php } ?>
        </tbody> 
    </table>
</div>