<div class="row">
	<div class="col-md-12">
		<h1>Productos</h1>
	</div>
</div>
			
			
<div class="row">
	<?php foreach ($this->product as $key){ ?>
	<div class="col-md-3 ">
		<center>
			<a href="/home/detalleproducto/id/<?php echo $key["id"]; ?>"><img src="/<?php echo $key["imagen"]; ?>" WIDTH = '250' HEIGHT = '250' />
				<?php echo $key["nombre"]; ?></h1>
			</a><br>
		</center>
	</div>
	<?php } ?>
</div> 



