<div class="container">
<div class="row">
	<div class="col-md-4">
		<img src="/img/logo-2.png" style="width: 350px;">
	</div>
	<div class="col-md-8">
<!-- 		<div class="text-center" style="margin-top: 80px;">
			<h4>Se ha enviado un correo con el proceso de la recuperación de tu contraseña.</h4>
		</div> -->

	  <div class="row mt-5">
	    <div class="col-md-12 text-center mt-4">
	      <span class="title-art">Se ha enviado un correo con el proceso de la recuperación de tu contraseña.</span> 
	    </div>
	  </div>



	<div class="row mt-5">
		<div class="col-md-12 text-center">
        <a href="/home/login" class="stylebutton btn btn-primary botones" style="font-size: 19px; color:rgb(255, 252, 252); width: 50%;height: 100%; padding-top: 12px; padding-left: 10px;">
           Iniciar Sesión!
        </a> 
        </div>
	</div>


	</div>
</div>
</div>